language: node_js
node_js:
  - '10'

before_install:
  - npm install -g greenkeeper-lockfile

install:
  - greenkeeper-lockfile-update
  - npm install
  - npm run build

script:
  - npm run test_with_report
  - greenkeeper-lockfile-upload

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release